
services:
  php-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: php_web_app
    volumes:
      - .:/app
    ports:
      - 8083:80
    env_file:
    # pour developpement
      - .env
    networks:
      - infra_central_net
      
  php-cli:
     build:
       context: .
       dockerfile: Dockerfile.cli
     container_name: php_cli_app
     volumes:
       - ./src:/app
     working_dir: /app
     env_file:
       - .env
     networks:
       - infra_central_net
     tty: true
     stdin_open: true


   

networks:
  infra_central_net:
    external: true
